name              'sshd-service'
maintainer        'Conjur, Inc.'
maintainer_email  'jon@conjur.net'
license           'MIT'
description       'Provides some cross platform sanity for ssh(d)'
version           '1.0.0'
